feat(char): add auto-jump/auto-motion option when using labels, closes #183
folke/flash.nvim pull request #281
Opened 2023-11-25 16:53 UTC by MyyPo

A solution for https://github.com/folke/flash.nvim/issues/183 I've been using locally. 

Currently can be enabled by setting **autojump** to **true**

```
modes = {
    char = {
        jump_labels = true,
        jump = {
            autojump = true,
        },
    },
}
```

2023-12-07 08:47 UTC, mintelm requested changes

2024-03-29 03:09 UTC, tmwatchanan commented
Tested this and it works quite well. The backdrop highlight disappears after the auto jump. Can you please consider merge this PR?

2024-04-22 08:52 UTC, rubiin approved these changes

2024-05-16 08:15 UTC, mintelm commented
any updates on this PR?

2024-06-01 19:03 UTC, mcdax commented
Any chance to getting it finally merged?

2024-06-01 19:13 UTC, merged

2024-06-01 19:13 UTC, folke commented
Done, sorry for the delay!

2024-06-13 16:17 UTC, tsakirist commented
This doesn't work for pending operator mode when there is only one hit. It still displays the label and you have to press the label to execute.

2024-06-13 19:31 UTC, myypo commented
> This doesn't work for operator pending mode when there is only one hit. It still displays the label and you have to press the label to execute.

Unless I am missing something, it works for me for char mode. For example, using running `df.`. If it isn't related to `f/t` motions it is just a different issue.
 
 ```
    -- options used when flash is activated through
    -- `f`, `F`, `t`, `T`, `;` and `,` motions
 ```